### ISSUE TITLE
webpack統合　buildエラー

### ISSUE THREAD

**Issue by TakuyaTaniguchi** [YuzuruSano/suitosha_base_static_html#14]
docker環境内でbuildするとエラーを吐く
```
/Users/oikaze/work/docker-php7.1/html/static_html_skelton/node_modules/snapdragon/lib/parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^
```

関連する[issue](https://github.com/BrowserSync/browser-sync/issues/1622)がありBowserのバージョンを下げても同様のエラーがでた。
docckerディレクトリ外だと正常にbuildできた。

**Comment by YuzuruSano** [comment]
@TakuyaTaniguchi 
これはdockerにシェルで入ってその状態でbuildしているのかな？
それともcd 作業ディレクトリしてそこでbuildしている状態？？

**Comment by TakuyaTaniguchi** [comment]
cd 作業ディレクトリしてそこでbuildしている状態　です。

だから関係無いと思ってるんですけど...なぜかそこだけでエラー出るんですよね。

**Comment by YuzuruSano** [comment]
@TakuyaTaniguchi 
なるほど、ディレクトリのパーミッションとかかな
