### ISSUE TITLE
mainタグのIE11対応

### ISSUE THREAD

**Issue by iyonaga** [YuzuruSano/suitosha_base_static_html#15]
IE11ではデフォルトでmainタグがinline要素になってしまうので、
他のブラウザと合わせるために`_reset.scss`に下記を追加した方が良いかと思いますー

```
main {
  display: block;
}
```

**Comment by YuzuruSano** [comment]
@iyonaga 
おぉ、この設定追加してなかったか...
ありがとうございまっす！
次回のアップデートで追加します〜
