### ISSUE TITLE
compile is very slow

### ISSUE THREAD

**Issue by hltree** [YuzuruSano/suitosha_base_static_html#28]
## 内容

```
$ npm run build
or
$ yarn build
```
としたとき、完了するまでに40~60秒かかります。

これが一般的な数字なのかはわかりませんが、とにかく早くしたいとおもっています。

以前調査したときは画像処理系のモジュールでかなり詰まっていました。
未だに解決はしていません。

具体的な対応策を知っていたら教えてください。

**Comment by YuzuruSano** [comment]
@hltree 
これ、pngの処理で結構詰まるので省くか他のライブラリに置き換えかな。

画像の処理だけbuildから切り出してもいいかも

**Comment by hltree** [comment]
https://github.com/YuzuruSano/static_html_skelton/tree/feat/webpack5

にて解決していると思いますので、閉じます。
